// Generated by Lasy AI - https://lasy.ai
"use client";

import { useEffect } from "react";
import { usePathname, useRouter } from "next/navigation";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";
import { AuthProvider, useAuth } from "@/contexts/AuthContext";
import { Loader2 } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Componente de proteção de rotas
function RouteGuard({ children }: { children: React.ReactNode }) {
  const { user, loading } = useAuth();
  const pathname = usePathname();
  const router = useRouter();

  useEffect(() => {
    // Se está na página de login, não fazer nada
    if (pathname === '/login') {
      return;
    }

    // Se não está carregando e não tem usuário, redirecionar para login
    if (!loading && !user) {
      router.push('/login');
    }
  }, [user, loading, pathname, router]);

  // Se está na página de login, renderizar normalmente
  if (pathname === '/login') {
    return <>{children}</>;
  }

  // Se está carregando, mostrar loader
  if (loading) {
    return (
      <div className="min-h-screen bg-gradient-to-b from-[#020617] to-[#020814] flex items-center justify-center">
        <div className="text-center">
          <Loader2 className="w-12 h-12 text-[#3B82F6] animate-spin mx-auto mb-4" />
          <p className="text-white text-lg">Carregando...</p>
        </div>
      </div>
    );
  }

  // Se não tem usuário, não renderizar nada (vai redirecionar)
  if (!user) {
    return null;
  }

  // Se tem usuário, renderizar normalmente
  return <>{children}</>;
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
        <title>Nexo - Seu Hub Completo para Estudos</title>
        <meta name="description" content="Plataforma completa para estudantes com dashboard, planejamento, timer Pomodoro, analytics e muito mais" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <RouteGuard>
            {children}
          </RouteGuard>
        </AuthProvider>
      </body>
    </html>
  );
}
